version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt-get update
      - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      - deb https://apt.dockerproject.org/repo ubuntu-xenial main
      - apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
      - apt-get install docker-engine
      - usermod -aG docker $USER
      - service docker start
  pre_build:
    commands:
      - ./test/configure.sh
      - ./test/setup.sh
      - docker run -d -P selenium/standalone-chrome
  build:
    commands:
      - ./test/test.sh
  post_build:
    commands:
      - ./test/teardown.js
artifacts:
  files:
    - ./test/debug.log
    - ./test/output.log
